### ISSUE TITLE
Copyright issues

### ISSUE THREAD

**Issue by anonymone** [WangChuan157/MOPIO#1]
Hi, Wang  
I am so glad to see that you use our platEMO.  And I have a good news to you that we have uploaded the latest version of the platform to github.[Here](https://github.com/BIMK/PlatEMO). The  previous web is also avilable for downloading. And we also hope you can PR you great idea to the official repo and write a short README in your repo for an acknowlagement  as our license required.

**Comment by WangChuan157** [comment]
That's all right, sorry for noticing this issues for such a long time.

**Comment by WangChuan157** [comment]
That's all right, sorry for noticing this issues after such a long time.

**Comment by yh-sh** [comment]
That's all right, sorry for noticing this message after such a long time.

**Comment by anonymone** [comment]
Thanks for your response.
ps. It is PlatEMO, Not PlatMO, it could be seen as a mistake? 😄

**Comment by yh-sh** [comment]
Rewrite it correctly, thanks for your support.

> Thanks for your response.
> ps. It is PlatEMO, Not PlatMO, it could be seen as a mistake? 😄
